### ISSUE TITLE
/ returning a cloudflare 520 while other endpoints work

### ISSUE THREAD

**Issue by fourjr** [RoyaleAPI/cr-api#272]
Request URLs that failed:
- https://api.royaleapi.com/
- https://api.cr-api.com/

Request URLs that worked:
- https://api.royaleapi.com/player/2P0LYQ
- https://api.cr-api.com/player/2P0LYQ

All requests are done with the same authentication.     
I did quite a number of requests to `/` so I don't think I requested at the exact moment when the API went down

**EDIT**: I tried `/a` for both domains and it returned a 520 as well. I think it's an issue with 404 handling

**Comment by fourjr** [comment]
http://api.cr-api.com/clan/
http://api.cr-api.com/player/

also returns 520

**Comment by fourjr** [comment]
http://api.cr-api.com/clan/
http://api.cr-api.com/player/

also returns 520

**Comment by selfish** [comment]
FUCK ME, @fourjr this was a great catch on your end.
Took me a few good nights of investigations to figure it out, but what was happening is that some 3rd party cache middleware I was using was thrown into an infinite loop on 404 errors, and crashed a node of the API every time a 404 occurred.

In fact, this is one of the best optimizations I've done, and I'd expect to see the performance increas not that it is:
Fixed in `v10.6.14`

Really great catch. Thanks.
